[workspace]

members = [
    "netlink-sys",
    "netlink-packet-core",
    "netlink-packet-utils",
    "netlink-packet-route",
    "netlink-packet-audit",
    "netlink-packet-sock-diag",
    "netlink-proto",
    "rtnetlink",
    "audit",
]

[patch.crates-io]
netlink-sys = { path = "netlink-sys" }
netlink-packet-core = { path = "netlink-packet-core" }
netlink-packet-utils = { path = "netlink-packet-utils" }
netlink-packet-route = { path = "netlink-packet-route" }
netlink-packet-audit = { path = "netlink-packet-audit" }
netlink-packet-sock-diag = { path = "netlink-packet-sock-diag" }
netlink-proto = { path = "netlink-proto" }
rtnetlink = { path = "rtnetlink" }
audit = { path = "audit" }
